### ISSUE TITLE
Similarity proteins search (like foldseek)

### ISSUE THREAD

**Issue by xnought** [xnought/venome#17]
My first thought is using the alphafold model embeddings to do similarity search.

@amandasinha I think you said you were interested in similarity between proteins? Any other thoughts on this?

## Main idea

For a protein wiki entry, we can show top 10 similar proteins from PDB using foldseek.

**Comment by xnought** [comment]
It might be interesting asking the venom lab people what approaches are in the research literature on this

**Comment by xnought** [comment]
Oh I think Michael mentioned something about protein blast, but I'm too ignorant to make an conclusions if that is helpful or not

**Comment by myouk** [comment]
Similarity searches are broad, and there are multiple ways to go about this:

-one strategy is using protein blast and the amino acid sequences in the venom text file.
 This puts the amino acid sequences up against published and reviewed sequences of known and reported proteins. I think this method is good if you want to uncover slight discrepancies in sequence. This can lead to investigations to understand why proteins within a single species, or even across species, have slight sequential differences in their proteins (even though they may perform the same function). This can be streamlined, though, because currently, I manually upload files to the website. 

-another strategy I'm trying to figure out on our cluster is Foldseek. This method doesn't utilize sequence data to perform the comparisons but instead uses the structure and orientation of the "backbone" of the protein to find matches that may be interesting. 

I might be able to meet with a Prof to see about this because it would be much more efficient to drop in the 400+ pdb files and just let the program in the cluster do its thing. I'm just hesitant to do this right away because I don't want to create millions of files by mistake

**Comment by myouk** [comment]
a "family" of Gh wasp venom proteins found to be mimics of a type of fruit fly immune receptor (PDB code: 4LXR--what I showed in our meeting) are as follows:

Gh_Comp13781_c0_seq1
Gh_Comp2027_c0_seq2
Gh_Comp2027_c0_seq6
Gh_Comp4646_c0_seq11
Gh_Comp2027_c0_seq1
Gh_Comp6788_c0_seq1
Gh_Comp4656_c0_seq5
Gh_Comp2027_c0_seq10
Gh_Comp4656_c0_seq2
Gh_comp6082_c0_seq1
Gh_comp1786_c0_seq1

**Comment by xnought** [comment]
Awesome, this is the [foldseek](https://www.biorxiv.org/content/10.1101/2022.02.07.479398v4.full.pdf), right?

**Comment by myouk** [comment]
> Awesome, this is the [foldseek](https://www.biorxiv.org/content/10.1101/2022.02.07.479398v4.full.pdf), right?

Yes!

**Comment by myouk** [comment]
I'm meeting with Professor Juan Vanegas next week to go through and set up the databases and whatever else I'll need to run the program, I'll share what comes from running foldseek with you all too

**Comment by xnought** [comment]
Amazing!

**Comment by xnought** [comment]
Note to self:  added a python interface for foldseek easy-search https://github.com/xnought/foldseek-bindings
